version : "3"
services:
  ebp-mongo:
    image: mongo:3.7
    container_name: ebp-mongo
    volumes:
      - ./.data/db:/data/db
    ports:
      - 27017:27017

  ebp-backend:
    container_name: ebp-backend
    image: ebp-backend
    build: .
    command: npm start
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
      - ./env:/app/env
    ports:
      - 3000:3000
    links:
      - ebp-mongo

  swagger_ui:
    environment:
      - API_URL=/api_doc/main.yml
    image: swaggerapi/swagger-ui
    volumes:
      - ./api_doc:/usr/share/nginx/html/api_doc
    restart: always
    ports:
      - 9001:8080
