version : "3"
services:

  ebp-backend:
    environment:
        - NODE_ENV=production
    container_name: ebp-backend
    image: ebp-backend
    build: .
    command: npm start
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
      - ./env:/app/env
    ports:
      - 3000:3000

  swagger_ui:
    environment:
      - API_URL=/api_doc/main.yml
    image: swaggerapi/swagger-ui
    volumes:
      - ./api_doc:/usr/share/nginx/html/api_doc
    restart: always
    ports:
      - 9001:8080
