version: '3'
services:
  ebp-frontend:
    container_name: ebp-frontend
    image: nginx:alpine
    ports:
      - 80:80

    volumes:
      - ./nginx/proxy.prod.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/www/dist

  cr-events-proxy:
    container_name: cr-events-proxy
    image: nginx:alpine
    ports:
      - 3002:3002

    volumes:
      - ./nginx/proxy.prod.events.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/www/dist
