version: '3'
services:
  ebp-frontend:
    container_name: ebp-frontend
    image: nginx:alpine
    ports:
      - 3001:3001
#    build: .

    volumes:
      - ./nginx/proxy.prod.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/www/dist
