openapi: 3.0.1

info:
  title: EBP back-end api
  description: The EBP backend
#   termsOfService:
  contact:
    name: Elastos.Community
    url: https://github.com/elastos/Elastos.Community/issues
#    email: liyangwood@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0

servers:
- url: http://localhost:3000
  description: dev server

tags:
- name: test
  description: test api, only available in dev env.

paths:
  /test/hello:
    $ref: "./path/test/hello.yml"

components:
  schemas:

